/* tslint:disable */
/* eslint-disable */
/**
 * Big Tech Night
 * The Big Tech Night API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import {
    DUMMY_BASE_URL,
    assertParamExists,
    setBearerAuthToObject,
    setSearchParams,
    serializeDataIfNeeded,
    toPathString,
    createRequestFunction,
} from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 *
 * @export
 * @interface ActionDto
 */
export interface ActionDto {
    /**
     * Уникальный идентификатор действия
     * @type {string}
     * @memberof ActionDto
     */
    id: string;
    /**
     * Название действия
     * @type {string}
     * @memberof ActionDto
     */
    name: string;
    /**
     * Описание действия
     * @type {string}
     * @memberof ActionDto
     */
    description: string;
    /**
     * Стоимость действия
     * @type {number}
     * @memberof ActionDto
     */
    cost: number;
    /**
     * Прибыли и влияние действия (опционально)
     * @type {ProfitsDto}
     * @memberof ActionDto
     */
    profits?: ProfitsDto;
    /**
     * Список возможных событий для данного действия
     * @type {Array<GameEventDto>}
     * @memberof ActionDto
     */
    events: Array<GameEventDto>;
}
/**
 *
 * @export
 * @interface AllChoicesDto
 */
export interface AllChoicesDto {
    /**
     * Выбранные юниты
     * @type {Array<string>}
     * @memberof AllChoicesDto
     */
    units: Array<string>;
    /**
     * Выбранные проекты
     * @type {Array<string>}
     * @memberof AllChoicesDto
     */
    projects: Array<string>;
    /**
     * Выбранные действия
     * @type {Array<string>}
     * @memberof AllChoicesDto
     */
    actions: Array<string>;
}
/**
 *
 * @export
 * @interface BadRequestErrorDto
 */
export interface BadRequestErrorDto {
    /**
     * HTTP статус код ошибки
     * @type {number}
     * @memberof BadRequestErrorDto
     */
    statusCode: number;
    /**
     * Сообщение об ошибке валидации или игровой логики
     * @type {BadRequestErrorMessages}
     * @memberof BadRequestErrorDto
     */
    message: BadRequestErrorMessages;
    /**
     * Тип ошибки
     * @type {string}
     * @memberof BadRequestErrorDto
     */
    error: string;
}

/**
 * Сообщение об ошибке валидации или игровой логики
 * @export
 * @enum {string}
 */

export const BadRequestErrorMessages = {
    Game_is_finished: 'Game is finished',
    You_can_select_only_one_unit_or_projects: 'You can select only one unit or projects',
    You_must_select_at_least_one_project: 'You must select at least one project',
    You_must_select_action: 'You must select action',
    No_rounds_found: 'No rounds found',
    No_more_quiz_choices: 'No more quiz choices',
    Unit_not_found: 'Unit not found',
    You_must_select_two_projects: 'You must select two projects',
    Not_enough_cash: 'Not enough cash',
    Game_is_not_finished: 'Game is not finished',
    Action_not_found: 'Action not found',
    Name_not_available: 'Name not available',
} as const;

export type BadRequestErrorMessages =
    (typeof BadRequestErrorMessages)[keyof typeof BadRequestErrorMessages];

/**
 *
 * @export
 * @interface CheckNameDto
 */
export interface CheckNameDto {
    /**
     * Имя пользователя
     * @type {string}
     * @memberof CheckNameDto
     */
    name: string;
}
/**
 *
 * @export
 * @interface CheckNameResponseDto
 */
export interface CheckNameResponseDto {
    /**
     * Доступно ли имя
     * @type {boolean}
     * @memberof CheckNameResponseDto
     */
    isAvailable: boolean;
}
/**
 *
 * @export
 * @interface CurrentBalanceDto
 */
export interface CurrentBalanceDto {
    /**
     * Текущий баланс игрока
     * @type {number}
     * @memberof CurrentBalanceDto
     */
    cash: number;
    /**
     * Скорость разработки в текущем балансе
     * @type {number}
     * @memberof CurrentBalanceDto
     */
    developingSpeed: number;
    /**
     * Технический долг в текущем балансе
     * @type {number}
     * @memberof CurrentBalanceDto
     */
    techDebt: number;
}
/**
 *
 * @export
 * @interface CurrentGameStateDto
 */
export interface CurrentGameStateDto {
    /**
     * ID текущего раунда
     * @type {string}
     * @memberof CurrentGameStateDto
     */
    currentRoundId: string;
    /**
     * Текущий баланс игрока
     * @type {CurrentBalanceDto}
     * @memberof CurrentGameStateDto
     */
    currentBalance: CurrentBalanceDto;
    /**
     * Тип текущего экрана
     * @type {ScreenType}
     * @memberof CurrentGameStateDto
     */
    screenType: ScreenType;
    /**
     * Выбранные действия
     * @type {Array<string>}
     * @memberof CurrentGameStateDto
     */
    selectedActionIds?: Array<string>;
    /**
     * Выбранные проекты
     * @type {Array<string>}
     * @memberof CurrentGameStateDto
     */
    selectedProjectIds?: Array<string>;
    /**
     * Текущий квиз
     * @type {string}
     * @memberof CurrentGameStateDto
     */
    quizId?: string;
    /**
     * Игра закончена
     * @type {boolean}
     * @memberof CurrentGameStateDto
     */
    isFinished?: boolean;
}

/**
 *
 * @export
 * @interface CurrentRoundStatsDto
 */
export interface CurrentRoundStatsDto {
    /**
     * Заработанные деньги в текущем раунде
     * @type {number}
     * @memberof CurrentRoundStatsDto
     */
    earned_cash: number;
    /**
     * Накопленный технический долг в текущем раунде
     * @type {number}
     * @memberof CurrentRoundStatsDto
     */
    earned_techDebt: number;
    /**
     * Накопленная скорость разработки в текущем раунде
     * @type {number}
     * @memberof CurrentRoundStatsDto
     */
    earned_developingSpeed: number;
    /**
     * Начальный баланс в текущем раунде
     * @type {number}
     * @memberof CurrentRoundStatsDto
     */
    start_cash: number;
    /**
     * Начальный технический долг в текущем раунде
     * @type {number}
     * @memberof CurrentRoundStatsDto
     */
    start_techDebt: number;
    /**
     * Начальная скорость разработки в текущем раунде
     * @type {number}
     * @memberof CurrentRoundStatsDto
     */
    start_developingSpeed: number;
}
/**
 * Тип события
 * @export
 * @enum {string}
 */

export const EventType = {
    BAD: 'BAD',
    GOOD: 'GOOD',
    SUPERBAD: 'SUPERBAD',
} as const;

export type EventType = (typeof EventType)[keyof typeof EventType];

/**
 *
 * @export
 * @interface GameDto
 */
export interface GameDto {
    /**
     * Начальный баланс игры
     * @type {number}
     * @memberof GameDto
     */
    statCash: number;
    /**
     * Начальный долг игры
     * @type {number}
     * @memberof GameDto
     */
    statTechDebt: number;
    /**
     * Начальная скорость разработки игры
     * @type {number}
     * @memberof GameDto
     */
    statDevelopingSpeed: number;
    /**
     * Список раундов в игре
     * @type {Array<RoundDto>}
     * @memberof GameDto
     */
    rounds: Array<RoundDto>;
}
/**
 *
 * @export
 * @interface GameEventDto
 */
export interface GameEventDto {
    /**
     * Уникальный идентификатор события
     * @type {string}
     * @memberof GameEventDto
     */
    id: string;
    /**
     * Тип события
     * @type {EventType}
     * @memberof GameEventDto
     */
    type: EventType;
    /**
     * Описание события
     * @type {string}
     * @memberof GameEventDto
     */
    description: string;
    /**
     * Прибыли и влияние проекта (опционально)
     * @type {ProfitsDto}
     * @memberof GameEventDto
     */
    profits?: ProfitsDto;
}

/**
 *
 * @export
 * @interface GameResultDto
 */
export interface GameResultDto {
    /**
     * Текущий баланс игрока
     * @type {number}
     * @memberof GameResultDto
     */
    cash: number;
    /**
     * Текущий баланс игрока
     * @type {number}
     * @memberof GameResultDto
     */
    techDebt: number;
    /**
     * Текущий баланс игрока
     * @type {number}
     * @memberof GameResultDto
     */
    developingSpeed: number;
    /**
     * Место игрока в игре
     * @type {number}
     * @memberof GameResultDto
     */
    userPlace: number;
    /**
     * Имя игрока
     * @type {string}
     * @memberof GameResultDto
     */
    userName: string;
}
/**
 *
 * @export
 * @interface InternalServerErrorDto
 */
export interface InternalServerErrorDto {
    /**
     * HTTP статус код ошибки
     * @type {number}
     * @memberof InternalServerErrorDto
     */
    statusCode: number;
    /**
     * Сообщение об внутренней ошибке сервера
     * @type {string}
     * @memberof InternalServerErrorDto
     */
    message: string;
    /**
     * Тип ошибки
     * @type {string}
     * @memberof InternalServerErrorDto
     */
    error: string;
}
/**
 *
 * @export
 * @interface LeaderBoardDto
 */
export interface LeaderBoardDto {
    /**
     * Место игрока в игре
     * @type {number}
     * @memberof LeaderBoardDto
     */
    place: number;
    /**
     * Баланс игрока
     * @type {number}
     * @memberof LeaderBoardDto
     */
    cash: number;
    /**
     * Имя игрока
     * @type {string}
     * @memberof LeaderBoardDto
     */
    name: string;
}
/**
 *
 * @export
 * @interface LeaderboardResponseDto
 */
export interface LeaderboardResponseDto {
    /**
     * Список игроков на текущей странице
     * @type {Array<LeaderBoardDto>}
     * @memberof LeaderboardResponseDto
     */
    players: Array<LeaderBoardDto>;
    /**
     * Общее количество завершивших игру игроков
     * @type {number}
     * @memberof LeaderboardResponseDto
     */
    totalPlayers: number;
    /**
     * Общее количество страниц
     * @type {number}
     * @memberof LeaderboardResponseDto
     */
    totalPages: number;
    /**
     * Текущая страница
     * @type {number}
     * @memberof LeaderboardResponseDto
     */
    currentPage: number;
    /**
     * Количество записей на странице
     * @type {number}
     * @memberof LeaderboardResponseDto
     */
    pageSize: number;
    /**
     * Есть ли следующая страница
     * @type {boolean}
     * @memberof LeaderboardResponseDto
     */
    hasNextPage: boolean;
    /**
     * Есть ли предыдущая страница
     * @type {boolean}
     * @memberof LeaderboardResponseDto
     */
    hasPreviousPage: boolean;
}
/**
 *
 * @export
 * @interface ProfitsDto
 */
export interface ProfitsDto {
    /**
     * Влияние на скорость разработки
     * @type {number}
     * @memberof ProfitsDto
     */
    speed: number;
    /**
     * Влияние на технический долг
     * @type {number}
     * @memberof ProfitsDto
     */
    techDebt: number;
    /**
     * Влияние на зарплату/бюджет
     * @type {number}
     * @memberof ProfitsDto
     */
    cash: number;
}
/**
 *
 * @export
 * @interface ProjectDto
 */
export interface ProjectDto {
    /**
     * Уникальный идентификатор проекта
     * @type {string}
     * @memberof ProjectDto
     */
    id: string;
    /**
     * Название проекта
     * @type {string}
     * @memberof ProjectDto
     */
    name: string;
    /**
     * Описание проекта
     * @type {string}
     * @memberof ProjectDto
     */
    description: string;
    /**
     * Тип проекта
     * @type {string}
     * @memberof ProjectDto
     */
    type: ProjectDtoTypeEnum;
    /**
     * Стоимость проекта
     * @type {number}
     * @memberof ProjectDto
     */
    cost: number;
    /**
     * Прибыли и влияние проекта (опционально)
     * @type {ProfitsDto}
     * @memberof ProjectDto
     */
    profits?: ProfitsDto;
    /**
     * Список возможных событий для данного проекта
     * @type {Array<GameEventDto>}
     * @memberof ProjectDto
     */
    events: Array<GameEventDto>;
}

export const ProjectDtoTypeEnum = {
    product: 'product',
    marketing: 'marketing',
    techDebt: 'techDebt',
} as const;

export type ProjectDtoTypeEnum = (typeof ProjectDtoTypeEnum)[keyof typeof ProjectDtoTypeEnum];

/**
 *
 * @export
 * @interface QuizDto
 */
export interface QuizDto {
    /**
     * Уникальный идентификатор викторины
     * @type {string}
     * @memberof QuizDto
     */
    id: string;
    /**
     * Название категории викторины
     * @type {string}
     * @memberof QuizDto
     */
    name: string;
    /**
     * Описание категории викторины
     * @type {string}
     * @memberof QuizDto
     */
    description: string;
    /**
     * Тема викторины
     * @type {string}
     * @memberof QuizDto
     */
    theme: string;
    /**
     * Список юнитов/технологий в данной категории
     * @type {Array<UnitDto>}
     * @memberof QuizDto
     */
    units: Array<UnitDto>;
}
/**
 *
 * @export
 * @interface RoundDto
 */
export interface RoundDto {
    /**
     * Уникальный идентификатор раунда
     * @type {string}
     * @memberof RoundDto
     */
    id: string;
    /**
     * Название раунда
     * @type {string}
     * @memberof RoundDto
     */
    name: string;
    /**
     * Список викторин в раунде
     * @type {Array<QuizDto>}
     * @memberof RoundDto
     */
    quiz: Array<QuizDto>;
    /**
     * Список проектов в раунде
     * @type {Array<ProjectDto>}
     * @memberof RoundDto
     */
    projects: Array<ProjectDto>;
    /**
     * Список действий в раунде
     * @type {Array<ActionDto>}
     * @memberof RoundDto
     */
    actions: Array<ActionDto>;
}
/**
 * Тип текущего экрана
 * @export
 * @enum {string}
 */

export const ScreenType = {
    quiz: 'quiz',
    projects: 'projects',
    actions: 'actions',
    result: 'result',
} as const;

export type ScreenType = (typeof ScreenType)[keyof typeof ScreenType];

/**
 *
 * @export
 * @interface SelectDto
 */
export interface SelectDto {
    /**
     * Уникальный идентификатор юнита, который выбирается
     * @type {string}
     * @memberof SelectDto
     */
    unitId?: string;
    /**
     * Уникальные идентификаторы проектов
     * @type {Array<string>}
     * @memberof SelectDto
     */
    projectIds?: Array<string>;
    /**
     * Уникальный идентификатор действия
     * @type {string}
     * @memberof SelectDto
     */
    actionId?: string;
}
/**
 *
 * @export
 * @interface SelectResultDto
 */
export interface SelectResultDto {
    /**
     * ID следующего квиза, если есть
     * @type {object}
     * @memberof SelectResultDto
     */
    nextQuiz?: object;
    /**
     * Нужно ли выбрать больше проектов в текущем раунде
     * @type {boolean}
     * @memberof SelectResultDto
     */
    needMoreProjects: boolean;
    /**
     * Выбранные юниты и проекты
     * @type {AllChoicesDto}
     * @memberof SelectResultDto
     */
    allChoices: AllChoicesDto;
    /**
     * ID следующего раунда, если текущий завершен
     * @type {object}
     * @memberof SelectResultDto
     */
    nextRound?: object;
    /**
     * Случайное событие, если есть
     * @type {GameEventDto}
     * @memberof SelectResultDto
     */
    event?: GameEventDto;
    /**
     * Игра завершена
     * @type {boolean}
     * @memberof SelectResultDto
     */
    finished: boolean;
    /**
     * Статистика текущего раунда
     * @type {CurrentRoundStatsDto}
     * @memberof SelectResultDto
     */
    currentRound: CurrentRoundStatsDto;
    /**
     * Текущий баланс игрока
     * @type {CurrentBalanceDto}
     * @memberof SelectResultDto
     */
    currentBalance: CurrentBalanceDto;
}
/**
 *
 * @export
 * @interface StartGameDto
 */
export interface StartGameDto {
    /**
     * Имя пользователя
     * @type {string}
     * @memberof StartGameDto
     */
    name: string;
}
/**
 *
 * @export
 * @interface StartGameResponseDto
 */
export interface StartGameResponseDto {
    /**
     * Токен игры
     * @type {string}
     * @memberof StartGameResponseDto
     */
    token: string;
}
/**
 *
 * @export
 * @interface UnauthorizedErrorDto
 */
export interface UnauthorizedErrorDto {
    /**
     * HTTP статус код ошибки
     * @type {number}
     * @memberof UnauthorizedErrorDto
     */
    statusCode: number;
    /**
     * Сообщение об ошибке авторизации
     * @type {UnauthorizedErrorMessages}
     * @memberof UnauthorizedErrorDto
     */
    message: UnauthorizedErrorMessages;
    /**
     * Тип ошибки
     * @type {string}
     * @memberof UnauthorizedErrorDto
     */
    error: string;
}

/**
 * Сообщение об ошибке авторизации
 * @export
 * @enum {string}
 */

export const UnauthorizedErrorMessages = {
    Authorization_header_is_missing: 'Authorization header is missing',
    Invalid_authorization_format__Use_Bearer_token:
        'Invalid authorization format. Use: Bearer {token}',
    Invalid_token: 'Invalid token',
    Token_validation_failed: 'Token validation failed',
} as const;

export type UnauthorizedErrorMessages =
    (typeof UnauthorizedErrorMessages)[keyof typeof UnauthorizedErrorMessages];

/**
 *
 * @export
 * @interface UnitDto
 */
export interface UnitDto {
    /**
     * Уникальный идентификатор юнита
     * @type {string}
     * @memberof UnitDto
     */
    id: string;
    /**
     * Название юнита/технологии
     * @type {string}
     * @memberof UnitDto
     */
    name: string;
    /**
     * Стоимость приобретения юнита
     * @type {number}
     * @memberof UnitDto
     */
    cost: number;
    /**
     * Прибыли и влияние юнита на различные метрики
     * @type {ProfitsDto}
     * @memberof UnitDto
     */
    profits: ProfitsDto;
    /**
     * Описание юнита
     * @type {string}
     * @memberof UnitDto
     */
    description: string;
    /**
     * Ссылка на иконку юнита
     * @type {string}
     * @memberof UnitDto
     */
    icon: string;
    /**
     * Список возможных событий для данного юнита
     * @type {Array<GameEventDto>}
     * @memberof UnitDto
     */
    events: Array<GameEventDto>;
}

/**
 * GameApi - axios parameter creator
 * @export
 */
export const GameApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Возвращает \"pong\" для проверки доступности API
         * @summary Проверка работы сервера
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        appControllerGetPingV1: async (
            options: RawAxiosRequestConfig = {},
        ): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/game/ping`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options };
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions =
                baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {
                ...localVarHeaderParameter,
                ...headersFromBaseOptions,
                ...options.headers,
            };

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Проверяет имя пользователя
         * @summary Проверить имя
         * @param {CheckNameDto} checkNameDto
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        checkName: async (
            checkNameDto: CheckNameDto,
            options: RawAxiosRequestConfig = {},
        ): Promise<RequestArgs> => {
            // verify required parameter 'checkNameDto' is not null or undefined
            assertParamExists('checkName', 'checkNameDto', checkNameDto);
            const localVarPath = `/api/v1/game/checkName`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options };
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions =
                baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {
                ...localVarHeaderParameter,
                ...headersFromBaseOptions,
                ...options.headers,
            };
            localVarRequestOptions.data = serializeDataIfNeeded(
                checkNameDto,
                localVarRequestOptions,
                configuration,
            );

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Возвращает текущий прогресс игры пользователя, включая раунд, баланс и статистику. Требует Bearer токен в заголовке Authorization.
         * @summary Получить текущее состояние игры
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        gameCurrent: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/game/current`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options };
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration);

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions =
                baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {
                ...localVarHeaderParameter,
                ...headersFromBaseOptions,
                ...options.headers,
            };

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Возвращает полную конфигурацию игры с раундами, викторинами, юнитами и проектами
         * @summary Получить данные игры
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        gameData: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/game/data`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options };
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions =
                baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {
                ...localVarHeaderParameter,
                ...headersFromBaseOptions,
                ...options.headers,
            };

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Возвращает таблицу лидеров игры
         * @summary Получить таблицу лидеров
         * @param {number} [page] Номер страницы (начиная с 1)
         * @param {number} [limit] Количество записей на странице
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        gameLeaderboard: async (
            page?: number,
            limit?: number,
            options: RawAxiosRequestConfig = {},
        ): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/game/leaderboard`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options };
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions =
                baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {
                ...localVarHeaderParameter,
                ...headersFromBaseOptions,
                ...options.headers,
            };

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Возвращает результат игры пользователя. Требует Bearer токен в заголовке Authorization.
         * @summary Получить результат игры
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        gameResult: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/game/result`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options };
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration);

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions =
                baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {
                ...localVarHeaderParameter,
                ...headersFromBaseOptions,
                ...options.headers,
            };

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Выбирает юнит или проект для игры. Требует Bearer токен в заголовке Authorization.
         * @summary Выбрать юнит или проект
         * @param {SelectDto} selectDto
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        gameSelect: async (
            selectDto: SelectDto,
            options: RawAxiosRequestConfig = {},
        ): Promise<RequestArgs> => {
            // verify required parameter 'selectDto' is not null or undefined
            assertParamExists('gameSelect', 'selectDto', selectDto);
            const localVarPath = `/api/v1/game/select`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options };
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration);

            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions =
                baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {
                ...localVarHeaderParameter,
                ...headersFromBaseOptions,
                ...options.headers,
            };
            localVarRequestOptions.data = serializeDataIfNeeded(
                selectDto,
                localVarRequestOptions,
                configuration,
            );

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Возвращает список всех пользователей с их балансами
         * @summary Начать игру
         * @param {StartGameDto} startGameDto
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        gameStart: async (
            startGameDto: StartGameDto,
            options: RawAxiosRequestConfig = {},
        ): Promise<RequestArgs> => {
            // verify required parameter 'startGameDto' is not null or undefined
            assertParamExists('gameStart', 'startGameDto', startGameDto);
            const localVarPath = `/api/v1/game/start`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options };
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions =
                baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {
                ...localVarHeaderParameter,
                ...headersFromBaseOptions,
                ...options.headers,
            };
            localVarRequestOptions.data = serializeDataIfNeeded(
                startGameDto,
                localVarRequestOptions,
                configuration,
            );

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    };
};

/**
 * GameApi - functional programming interface
 * @export
 */
export const GameApiFp = function (configuration?: Configuration) {
    const localVarAxiosParamCreator = GameApiAxiosParamCreator(configuration);
    return {
        /**
         * Возвращает \"pong\" для проверки доступности API
         * @summary Проверка работы сервера
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async appControllerGetPingV1(
            options?: RawAxiosRequestConfig,
        ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>> {
            const localVarAxiosArgs =
                await localVarAxiosParamCreator.appControllerGetPingV1(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath =
                operationServerMap['GameApi.appControllerGetPingV1']?.[localVarOperationServerIndex]
                    ?.url;
            return (axios, basePath) =>
                createRequestFunction(
                    localVarAxiosArgs,
                    globalAxios,
                    BASE_PATH,
                    configuration,
                )(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Проверяет имя пользователя
         * @summary Проверить имя
         * @param {CheckNameDto} checkNameDto
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async checkName(
            checkNameDto: CheckNameDto,
            options?: RawAxiosRequestConfig,
        ): Promise<
            (axios?: AxiosInstance, basePath?: string) => AxiosPromise<CheckNameResponseDto>
        > {
            const localVarAxiosArgs = await localVarAxiosParamCreator.checkName(
                checkNameDto,
                options,
            );
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath =
                operationServerMap['GameApi.checkName']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) =>
                createRequestFunction(
                    localVarAxiosArgs,
                    globalAxios,
                    BASE_PATH,
                    configuration,
                )(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Возвращает текущий прогресс игры пользователя, включая раунд, баланс и статистику. Требует Bearer токен в заголовке Authorization.
         * @summary Получить текущее состояние игры
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async gameCurrent(
            options?: RawAxiosRequestConfig,
        ): Promise<
            (axios?: AxiosInstance, basePath?: string) => AxiosPromise<CurrentGameStateDto>
        > {
            const localVarAxiosArgs = await localVarAxiosParamCreator.gameCurrent(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath =
                operationServerMap['GameApi.gameCurrent']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) =>
                createRequestFunction(
                    localVarAxiosArgs,
                    globalAxios,
                    BASE_PATH,
                    configuration,
                )(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Возвращает полную конфигурацию игры с раундами, викторинами, юнитами и проектами
         * @summary Получить данные игры
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async gameData(
            options?: RawAxiosRequestConfig,
        ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GameDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.gameData(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath =
                operationServerMap['GameApi.gameData']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) =>
                createRequestFunction(
                    localVarAxiosArgs,
                    globalAxios,
                    BASE_PATH,
                    configuration,
                )(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Возвращает таблицу лидеров игры
         * @summary Получить таблицу лидеров
         * @param {number} [page] Номер страницы (начиная с 1)
         * @param {number} [limit] Количество записей на странице
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async gameLeaderboard(
            page?: number,
            limit?: number,
            options?: RawAxiosRequestConfig,
        ): Promise<
            (axios?: AxiosInstance, basePath?: string) => AxiosPromise<LeaderboardResponseDto>
        > {
            const localVarAxiosArgs = await localVarAxiosParamCreator.gameLeaderboard(
                page,
                limit,
                options,
            );
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath =
                operationServerMap['GameApi.gameLeaderboard']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) =>
                createRequestFunction(
                    localVarAxiosArgs,
                    globalAxios,
                    BASE_PATH,
                    configuration,
                )(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Возвращает результат игры пользователя. Требует Bearer токен в заголовке Authorization.
         * @summary Получить результат игры
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async gameResult(
            options?: RawAxiosRequestConfig,
        ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GameResultDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.gameResult(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath =
                operationServerMap['GameApi.gameResult']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) =>
                createRequestFunction(
                    localVarAxiosArgs,
                    globalAxios,
                    BASE_PATH,
                    configuration,
                )(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Выбирает юнит или проект для игры. Требует Bearer токен в заголовке Authorization.
         * @summary Выбрать юнит или проект
         * @param {SelectDto} selectDto
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async gameSelect(
            selectDto: SelectDto,
            options?: RawAxiosRequestConfig,
        ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SelectResultDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.gameSelect(
                selectDto,
                options,
            );
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath =
                operationServerMap['GameApi.gameSelect']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) =>
                createRequestFunction(
                    localVarAxiosArgs,
                    globalAxios,
                    BASE_PATH,
                    configuration,
                )(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Возвращает список всех пользователей с их балансами
         * @summary Начать игру
         * @param {StartGameDto} startGameDto
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async gameStart(
            startGameDto: StartGameDto,
            options?: RawAxiosRequestConfig,
        ): Promise<
            (axios?: AxiosInstance, basePath?: string) => AxiosPromise<StartGameResponseDto>
        > {
            const localVarAxiosArgs = await localVarAxiosParamCreator.gameStart(
                startGameDto,
                options,
            );
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath =
                operationServerMap['GameApi.gameStart']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) =>
                createRequestFunction(
                    localVarAxiosArgs,
                    globalAxios,
                    BASE_PATH,
                    configuration,
                )(axios, localVarOperationServerBasePath || basePath);
        },
    };
};

/**
 * GameApi - factory interface
 * @export
 */
export const GameApiFactory = function (
    configuration?: Configuration,
    basePath?: string,
    axios?: AxiosInstance,
) {
    const localVarFp = GameApiFp(configuration);
    return {
        /**
         * Возвращает \"pong\" для проверки доступности API
         * @summary Проверка работы сервера
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        appControllerGetPingV1(options?: RawAxiosRequestConfig): AxiosPromise<string> {
            return localVarFp
                .appControllerGetPingV1(options)
                .then((request) => request(axios, basePath));
        },
        /**
         * Проверяет имя пользователя
         * @summary Проверить имя
         * @param {GameApiCheckNameRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        checkName(
            requestParameters: GameApiCheckNameRequest,
            options?: RawAxiosRequestConfig,
        ): AxiosPromise<CheckNameResponseDto> {
            return localVarFp
                .checkName(requestParameters.checkNameDto, options)
                .then((request) => request(axios, basePath));
        },
        /**
         * Возвращает текущий прогресс игры пользователя, включая раунд, баланс и статистику. Требует Bearer токен в заголовке Authorization.
         * @summary Получить текущее состояние игры
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        gameCurrent(options?: RawAxiosRequestConfig): AxiosPromise<CurrentGameStateDto> {
            return localVarFp.gameCurrent(options).then((request) => request(axios, basePath));
        },
        /**
         * Возвращает полную конфигурацию игры с раундами, викторинами, юнитами и проектами
         * @summary Получить данные игры
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        gameData(options?: RawAxiosRequestConfig): AxiosPromise<GameDto> {
            return localVarFp.gameData(options).then((request) => request(axios, basePath));
        },
        /**
         * Возвращает таблицу лидеров игры
         * @summary Получить таблицу лидеров
         * @param {GameApiGameLeaderboardRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        gameLeaderboard(
            requestParameters: GameApiGameLeaderboardRequest = {},
            options?: RawAxiosRequestConfig,
        ): AxiosPromise<LeaderboardResponseDto> {
            return localVarFp
                .gameLeaderboard(requestParameters.page, requestParameters.limit, options)
                .then((request) => request(axios, basePath));
        },
        /**
         * Возвращает результат игры пользователя. Требует Bearer токен в заголовке Authorization.
         * @summary Получить результат игры
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        gameResult(options?: RawAxiosRequestConfig): AxiosPromise<GameResultDto> {
            return localVarFp.gameResult(options).then((request) => request(axios, basePath));
        },
        /**
         * Выбирает юнит или проект для игры. Требует Bearer токен в заголовке Authorization.
         * @summary Выбрать юнит или проект
         * @param {GameApiGameSelectRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        gameSelect(
            requestParameters: GameApiGameSelectRequest,
            options?: RawAxiosRequestConfig,
        ): AxiosPromise<SelectResultDto> {
            return localVarFp
                .gameSelect(requestParameters.selectDto, options)
                .then((request) => request(axios, basePath));
        },
        /**
         * Возвращает список всех пользователей с их балансами
         * @summary Начать игру
         * @param {GameApiGameStartRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        gameStart(
            requestParameters: GameApiGameStartRequest,
            options?: RawAxiosRequestConfig,
        ): AxiosPromise<StartGameResponseDto> {
            return localVarFp
                .gameStart(requestParameters.startGameDto, options)
                .then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for checkName operation in GameApi.
 * @export
 * @interface GameApiCheckNameRequest
 */
export interface GameApiCheckNameRequest {
    /**
     *
     * @type {CheckNameDto}
     * @memberof GameApiCheckName
     */
    readonly checkNameDto: CheckNameDto;
}

/**
 * Request parameters for gameLeaderboard operation in GameApi.
 * @export
 * @interface GameApiGameLeaderboardRequest
 */
export interface GameApiGameLeaderboardRequest {
    /**
     * Номер страницы (начиная с 1)
     * @type {number}
     * @memberof GameApiGameLeaderboard
     */
    readonly page?: number;

    /**
     * Количество записей на странице
     * @type {number}
     * @memberof GameApiGameLeaderboard
     */
    readonly limit?: number;
}

/**
 * Request parameters for gameSelect operation in GameApi.
 * @export
 * @interface GameApiGameSelectRequest
 */
export interface GameApiGameSelectRequest {
    /**
     *
     * @type {SelectDto}
     * @memberof GameApiGameSelect
     */
    readonly selectDto: SelectDto;
}

/**
 * Request parameters for gameStart operation in GameApi.
 * @export
 * @interface GameApiGameStartRequest
 */
export interface GameApiGameStartRequest {
    /**
     *
     * @type {StartGameDto}
     * @memberof GameApiGameStart
     */
    readonly startGameDto: StartGameDto;
}

/**
 * GameApi - object-oriented interface
 * @export
 * @class GameApi
 * @extends {BaseAPI}
 */
export class GameApi extends BaseAPI {
    /**
     * Возвращает \"pong\" для проверки доступности API
     * @summary Проверка работы сервера
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GameApi
     */
    public appControllerGetPingV1(options?: RawAxiosRequestConfig) {
        return GameApiFp(this.configuration)
            .appControllerGetPingV1(options)
            .then((request) => request(this.axios, this.basePath));
    }

    /**
     * Проверяет имя пользователя
     * @summary Проверить имя
     * @param {GameApiCheckNameRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GameApi
     */
    public checkName(requestParameters: GameApiCheckNameRequest, options?: RawAxiosRequestConfig) {
        return GameApiFp(this.configuration)
            .checkName(requestParameters.checkNameDto, options)
            .then((request) => request(this.axios, this.basePath));
    }

    /**
     * Возвращает текущий прогресс игры пользователя, включая раунд, баланс и статистику. Требует Bearer токен в заголовке Authorization.
     * @summary Получить текущее состояние игры
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GameApi
     */
    public gameCurrent(options?: RawAxiosRequestConfig) {
        return GameApiFp(this.configuration)
            .gameCurrent(options)
            .then((request) => request(this.axios, this.basePath));
    }

    /**
     * Возвращает полную конфигурацию игры с раундами, викторинами, юнитами и проектами
     * @summary Получить данные игры
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GameApi
     */
    public gameData(options?: RawAxiosRequestConfig) {
        return GameApiFp(this.configuration)
            .gameData(options)
            .then((request) => request(this.axios, this.basePath));
    }

    /**
     * Возвращает таблицу лидеров игры
     * @summary Получить таблицу лидеров
     * @param {GameApiGameLeaderboardRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GameApi
     */
    public gameLeaderboard(
        requestParameters: GameApiGameLeaderboardRequest = {},
        options?: RawAxiosRequestConfig,
    ) {
        return GameApiFp(this.configuration)
            .gameLeaderboard(requestParameters.page, requestParameters.limit, options)
            .then((request) => request(this.axios, this.basePath));
    }

    /**
     * Возвращает результат игры пользователя. Требует Bearer токен в заголовке Authorization.
     * @summary Получить результат игры
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GameApi
     */
    public gameResult(options?: RawAxiosRequestConfig) {
        return GameApiFp(this.configuration)
            .gameResult(options)
            .then((request) => request(this.axios, this.basePath));
    }

    /**
     * Выбирает юнит или проект для игры. Требует Bearer токен в заголовке Authorization.
     * @summary Выбрать юнит или проект
     * @param {GameApiGameSelectRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GameApi
     */
    public gameSelect(
        requestParameters: GameApiGameSelectRequest,
        options?: RawAxiosRequestConfig,
    ) {
        return GameApiFp(this.configuration)
            .gameSelect(requestParameters.selectDto, options)
            .then((request) => request(this.axios, this.basePath));
    }

    /**
     * Возвращает список всех пользователей с их балансами
     * @summary Начать игру
     * @param {GameApiGameStartRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GameApi
     */
    public gameStart(requestParameters: GameApiGameStartRequest, options?: RawAxiosRequestConfig) {
        return GameApiFp(this.configuration)
            .gameStart(requestParameters.startGameDto, options)
            .then((request) => request(this.axios, this.basePath));
    }
}
